cc_library(
    name = "manageJson",
    srcs = ["manage.cc"],
    hdrs = ["manage.h"],
    data = ["//configs:all_configs"],
    deps = ["//third_party/json:nlohmann_json"],
    visibility = ["//Console:__pkg__"]
)